/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import javax.swing.JOptionPane;
import melt.Controller;
import melt.Model.Section;
import melt.Model.Test;

/**
 *
 * @author Fuhao
 */
public class SectionDetails extends javax.swing.JPanel {

    private Controller controller;
    private Test testObject;
    private TreePanel treePane;
    private Section sectionObject;

    /**
     * Creates new form SectionPanel
     */
    public SectionDetails() {
        initComponents();
    }
    public void deleteSection()
    {
        this.controller.deleteSection(testObject, sectionObject.getId());
        treePane.removeCurrentNode();
    }
    public SectionDetails(Controller controller, TreePanel treePane) {
        setOpaque(true);
        this.controller = controller;
        this.treePane = treePane;
        initComponents();
    }

    public void setTestObject(Test test) {
        this.testObject = test;
    }

    private boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");
    }

    public void setSectionObject(Section section) {
        this.sectionObject = section;
        preview();
    }

    private void preview() {
        if (sectionObject == null) {
            clear();
        } else {
            clear();
            txtName.setText(sectionObject.getName());
            txtInstructions.setText(sectionObject.getInstructions());
            txtTime.setText(Double.toString(sectionObject.getTime()));
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
        }
    }

    private void clear() {
        txtName.setText("");
        txtInstructions.setText("");
        txtTime.setText("");
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblInstructions = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInstructions = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        lblMinutes = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Snap ITC", 0, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Section Details");

        lblName.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Section Name");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblTime.setText("Time");

        lblInstructions.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblInstructions.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInstructions.setText("Instructions");

        txtInstructions.setColumns(20);
        txtInstructions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInstructions.setLineWrap(true);
        txtInstructions.setRows(5);
        jScrollPane3.setViewportView(txtInstructions);

        btnSave.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melt/View/Icons/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblMinutes.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblMinutes.setText("minutes");

        btnUpdate.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melt/View/Icons/update.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setMaximumSize(new java.awt.Dimension(63, 25));
        btnUpdate.setMinimumSize(new java.awt.Dimension(63, 25));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInstructions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMinutes))
                                    .addComponent(txtName)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstructions)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinutes))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().equals("") || txtInstructions.getText().equals("") || txtTime.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all the details for the section.");
        } else {
            String sectionName = txtName.getText();
            String sectionInstructions = txtInstructions.getText();
            String sectionTime = txtTime.getText();
            //check if section time field is a number - show message dialog in any other case
            if (isNumeric(sectionTime)) {
                double time = Double.parseDouble(sectionTime);
                Section newSection = this.controller.addSection(testObject, time, sectionName, sectionInstructions);
                this.treePane.addSectionNode(newSection);
                this.controller.updateXmlFile();

            } else {
                JOptionPane.showMessageDialog(this, "Please enter a number in the Time field.");
            }

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().equals("") || txtInstructions.getText().equals("") || txtTime.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all the details for the section.");
        } else {
            String sectionName = txtName.getText();
            String sectionInstructions = txtInstructions.getText();
            String sectionTime = txtTime.getText();
            //check if section time field is a number - show message dialog in any other case
            if (isNumeric(sectionTime)) {
                double time = Double.parseDouble(sectionTime);
                this.controller.updateSectionDetails(sectionObject, time, sectionName, sectionInstructions);
                this.controller.updateXmlFile();

            } else {
                JOptionPane.showMessageDialog(this, "Please enter a number in the Time field.");
            }

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblMinutes;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtInstructions;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
