/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import melt.Controller;
import melt.Model.Mcq;
import melt.Model.Question;
import melt.Model.Section;
import melt.Model.Subsection;
import melt.Model.Test;

/**
 *
 * @author mbaxkfx2
 */
public class StudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentPanel
     */
   
   private Controller controller;
   private SingleSectionPanel sectionPanel;
   private int sectionIndex = 1;
   private double score=0;
   private Test currentTest;
    StudentPanel(Controller controller) {
        initComponents();
        this.controller = controller;
        currentTest = controller.getTestBank().getTestById(1);
        sectionPanel = new SingleSectionPanel(currentTest.getSectionById(sectionIndex));
        scrollPane.setViewportView(sectionPanel);
        sectionPanel.showSection();
        

        
        //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NextButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        TimeLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();

        NextButton.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        TimeLabel.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        TimeLabel.setText("Time");

        scrollPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(TimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 593, Short.MAX_VALUE)
                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(NextButton)
                    .addComponent(TimeLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        //scrollPane.removeAll();
        
        sectionIndex++;
        //sectionPanel.setSectionObject(controller.getTestBank().getTestById(1).getSectionById(sectionIndex));
        //scrollPane.repaint();
        if(currentTest.getSectionById(sectionIndex)==null){
            sectionPanel.setPanelAnswers();
            JOptionPane.showMessageDialog(sectionPanel, "There are no more sections in the test, please submit the test.");
        }
        else{
            sectionPanel.setPanelAnswers();
            sectionPanel = new SingleSectionPanel(currentTest.getSectionById(sectionIndex));
            scrollPane.setViewportView(sectionPanel);
            sectionPanel.showSection();
            
            this.revalidate();
        }
        
       // scrollPane.revalidate();
        //scrollPane.repaint();


        //this.revalidate();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        double total = 0.0;
        for(Section section : currentTest.getSections()){
            for(Subsection subsection : section.getSubsections()){
                for(Question question : subsection.getQuestions()){
                    Mcq mcqQuestion = (Mcq) question;
                    total += mcqQuestion.getMark();
                    if(mcqQuestion.checkAnswer()){
                     score = score + mcqQuestion.getMark();
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(sectionPanel, score + " out of " + total);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
