/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import javax.swing.JOptionPane;
import melt.Controller;
import melt.Model.Section;
import melt.Model.Subsection;

/**
 *
 * @author Fuhao
 */
public class SubsectionDetails extends javax.swing.JPanel {

    private Controller controller;
    private Object fatherObject;
    private TreePanel treePane;
    private Subsection subsectionObject;

    /**
     * Creates new form SubsectionPanel
     */
    public SubsectionDetails() {
        initComponents();
    }

    public void deleteSubsection() {
        this.controller.deleteSubsection(fatherObject, subsectionObject.getId());
        treePane.removeCurrentNode();
    }

    public SubsectionDetails(Controller controller, TreePanel treePane) {
        setOpaque(true);
        this.controller = controller;
        this.treePane = treePane;
        initComponents();
    }

    public void setFatherObject(Object father) {
        this.fatherObject = father;
    }

    public void setSubsectionObject(Subsection subsection) {
        this.subsectionObject = subsection;
        preview();
    }

    private void preview() {
        if (subsectionObject == null) {
            clear();
        } else {
            subsectionName.setText(subsectionObject.getName());
        }
    }

    private void clear() {
        subsectionName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        subsectionName = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Snap ITC", 0, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Subsection Details");

        lblName.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Subsection Name:");

        subsectionName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subsectionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsectionNameActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melt/View/Icons/save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 256, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addGap(0, 256, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subsectionName, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subsectionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(saveButton)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subsectionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsectionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subsectionNameActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (this.subsectionName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a name for the subsection.");
        } else {
            String subName = this.subsectionName.getText();

            if (subsectionObject == null) {
                Subsection newSubsection = this.controller.addSubsection(fatherObject, subName);
                treePane.addSubSectionNode(newSubsection);
                this.controller.updateXmlFile();
            } else {
                this.controller.updateSubsectionDetails(subsectionObject, subName);
                this.controller.updateXmlFile();
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField subsectionName;
    // End of variables declaration//GEN-END:variables
}
