/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import javax.swing.AbstractListModel;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.ListModel;
import melt.Controller;
import melt.Model.TestBank;

/**
 *
 * @author mbaxkfx2
 */
public class TestList extends javax.swing.JPanel {
    private Controller controller;
    private AbstractListModel listModel;
    /**
     * Creates new form TestList
     */
   
    public TestList(Controller controller)
    {   
        this.controller = controller;
        initComponents();        
    }
    public void showAllTest()
    {   
    final String[] testNumber = new String[controller.getTestBank().getTests().size()];
    for(int i=0;i<controller.getTestBank().getTests().size();i++){
       testNumber[i] = controller.getTestBank().getTests().get(i).getName();
    }
    listModel = new AbstractListModel() {

        @Override
        public int getSize() {
            return testNumber.length;//To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Object getElementAt(int i) {
             return testNumber[i]; //To change body of generated methods, choose Tools | Templates.
        }
    };
    jList1.setModel(listModel);
    }
    public static void main(String args[])
    {   
        Controller controller;
        TestBank model = null;
        Viewer viewer = null;
        JFrame aframe = new JFrame();
        controller = new Controller(model,viewer,"melt.xml","");
        TestList details= new TestList(controller);
        controller.loadFromXmlFile();
        aframe.add(details);
        details.showAllTest();
        aframe.setSize(600, 440);
        aframe.setVisible(true);
        }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnTakeTest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        btnBack.setText("Back");

        btnTakeTest.setText("TakeTest");

        jList1.setBackground(new java.awt.Color(237, 236, 235));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265)
                        .addComponent(btnTakeTest)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnTakeTest))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTakeTest;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
