/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import melt.Controller;
import melt.Model.Test;

/**
 *
 * @author mbaxkfx2
 */
public class TestList extends javax.swing.JPanel {

    private Controller controller;
    private AbstractListModel listModel;
    private JPanel contentPane;
    private int testSelected;

    /**
     * Creates new form TestList
     */
    public TestList(JPanel contentPane, Controller controller) {
        this.controller = controller;
        initComponents();
        this.contentPane = contentPane;
        this.showAllTest();

    }

    public void showAllTest() {
        final Test[] tests = new Test[controller.getTestBank().getTests().size()];
        for (int i = 0; i < controller.getTestBank().getTests().size(); i++) {
            tests[i] = controller.getTestBank().getTestById(i + 1);
        }
        listModel = new AbstractListModel() {
            @Override
            public int getSize() {
                return tests.length;//To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getElementAt(int i) {
                return tests[i]; //To change body of generated methods, choose Tools | Templates.
            }
        };
        jList1.setModel(listModel);
        
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {
        CardLayout cardLayout7 = (CardLayout) contentPane.getLayout();
        cardLayout7.show(contentPane, "welcomePanel");    // TODO add your handling code here:

    }

    private void btnTakeTestActionPerformed(ActionEvent evt) {
        if(jList1.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "You need to select a test first.");
            return;
        }
        CardLayout cardLayout2 = (CardLayout) contentPane.getLayout();
        cardLayout2.show(contentPane, "takeTest");        // TODO add your handling code here:
        StudentPanel panel = (StudentPanel) contentPane.getComponent(2);
       
        
        panel.setTest(this.controller.getTest(jList1.getSelectedIndex() + 1));
        panel.startTest();//To change body of generated methods, choose Tools | Templates.
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnTakeTest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnTakeTest.setText("TakeTest");
        btnTakeTest.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeTestActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(237, 236, 235));
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(btnTakeTest)))
                .addContainerGap(150, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnBack)
                .addComponent(btnTakeTest))
                .addGap(29, 29, 29)));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTakeTest;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
