/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import javax.swing.JOptionPane;
import melt.Controller;
import melt.Model.Test;
import melt.Model.TestBank;

/**
 *
 * @author Maria
 */
public class TestDetails extends javax.swing.JPanel {

    private Controller controller;
    private TestBank testBankObject;
    private TreePanel treePanel;
    private Test testObject;

    /**
     * Creates new form TestDetails
     */
    public TestDetails() {
        initComponents();
    }
    
    public TestDetails(Controller controller, TreePanel treePanel) {
        setOpaque(true);
        this.controller = controller;
        this.treePanel = treePanel;
        initComponents();
    }

    public void setTestBankObject(TestBank testBankObject) {
        this.testBankObject = testBankObject;
    }

    public void setTestObject(Test testObject) {
        this.testObject = testObject;
        preview();
    }

    private void preview() {
        if (testObject == null) {
            clear();
        } else {
            clear();
            txtName.setText(testObject.getName());
            txtCreator.setText(testObject.getCreator());
            txtInstructions.setText(testObject.getInstructions());
            btnCreate.setEnabled(false);
            btnUpdate.setEnabled(true);
        }
    }

    private void clear() {
        txtName.setText("");
        txtCreator.setText("");
        txtInstructions.setText("");
        btnCreate.setEnabled(true);
        btnUpdate.setEnabled(false);
    }

    public void deleteTest()
    {
        this.controller.deleteTest(testObject.getId());
        treePanel.removeCurrentNode();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblCreator = new javax.swing.JLabel();
        txtCreator = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();
        txtInstructions = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Snap ITC", 0, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Test Details");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblName.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblName.setText("Test Name");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblCreator.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblCreator.setText("Created by");

        txtCreator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreatorActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblInstructions.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblInstructions.setText("Instructions");

        txtInstructions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructionsActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCreator)
                            .addComponent(lblName)
                            .addComponent(lblInstructions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(txtCreator)
                            .addComponent(txtName))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreator)
                    .addComponent(txtCreator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstructions)
                    .addComponent(txtInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnReset))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if (txtName.getText().equals("") || txtCreator.getText().equals("") || txtInstructions.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all details of the test");
        } else {
            String newTestName = txtName.getText();
            String newTestCreator = txtCreator.getText();
            String newTestInstructions = txtInstructions.getText();
            Test newTestObject = this.controller.addTest(newTestName, newTestCreator, newTestInstructions);
            treePanel.addTestNode(newTestObject);
            this.controller.updateXmlFile();
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtCreator.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreatorActionPerformed

    private void txtInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructionsActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().equals("") || txtCreator.getText().equals("") || txtInstructions.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all details of the test");
        } else {
            String newTestName = txtName.getText();
            String newTestCreator = txtCreator.getText();
            String newTestInstructions = txtInstructions.getText();
            this.controller.updateTestDetails(testObject, newTestName, newTestCreator, newTestInstructions);
            this.controller.updateXmlFile();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCreator;
    private javax.swing.JTextField txtInstructions;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
