/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import javax.swing.JOptionPane;
import melt.Controller;
import melt.Model.Test;
import melt.Model.TestBank;

/**
 *
 * @author Maria
 */
public class TestDetails extends javax.swing.JPanel {
    
    private Controller controller;
    private TestBank testBankObject;
    private TreePanel treePanel;
    private Test testObject;

    /**
     * Creates new form TestDetails
     */
    public TestDetails() {
        initComponents();
    }
    
    public TestDetails(Controller controller, TreePanel treePanel) {
        setOpaque(true);
        this.controller = controller;
        this.treePanel = treePanel;
        initComponents();
    }
    
    public void setTestBankObject(TestBank testBankObject) {
        this.testBankObject = testBankObject;
    }
    
    public void setTestObject(Test testObject) {
        this.testObject = testObject;
        preview();
    }
    
    private void preview() {
        if (testObject == null) {
            clear();
        } else {
            clear();
            txtName.setText(testObject.getName());
            txtCreator.setText(testObject.getCreator());
            txtInstructions.setText(testObject.getInstructions());
            btnSave.setEnabled(false);
            btnUpdate.setEnabled(true);
        }
    }
    
    private void clear() {
        txtName.setText("");
        txtCreator.setText("");
        txtInstructions.setText("");
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }
    
    public void deleteTest() {
        this.controller.deleteTest(testObject.getId());
        treePanel.removeCurrentNode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblCreator = new javax.swing.JLabel();
        txtCreator = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();
        txtInstructions = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Snap ITC", 0, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Test Details");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblName.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblName.setText("Test Name");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblCreator.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblCreator.setText("Created by");

        txtCreator.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreatorActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melt/View/Icons/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblInstructions.setFont(new java.awt.Font("MV Boli", 0, 15)); // NOI18N
        lblInstructions.setText("Instructions");

        txtInstructions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCreator)
                                    .addComponent(lblName)
                                    .addComponent(lblInstructions))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(txtCreator)
                                    .addComponent(txtName))))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreator)
                    .addComponent(txtCreator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstructions)
                    .addComponent(txtInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtName.getText().equals("") || txtCreator.getText().equals("") || txtInstructions.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter all details of the test");
        } else {
            
            String newTestName = txtName.getText();
            String newTestCreator = txtCreator.getText();
            String newTestInstructions = txtInstructions.getText();
            if (testObject == null) {
                Test newTestObject = this.controller.addTest(newTestName, newTestCreator, newTestInstructions);
                treePanel.addTestNode(newTestObject);
            } else {
                this.controller.updateTestDetails(testObject, newTestName, newTestCreator, newTestInstructions);
            }
         
            this.controller.updateXmlFile();            
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void txtCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreatorActionPerformed
    
    private void txtInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructionsActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCreator;
    private javax.swing.JTextField txtInstructions;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
