/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package melt.View;

import java.awt.CardLayout;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import melt.Controller;
import melt.Model.Test;

/**
 *
 * @author Maria
 */
public class TestList extends javax.swing.JPanel {

    private Controller controller;
    private AbstractListModel listModel;
    private JPanel contentPane;
    private int testSelected;

    /**
     * Creates new form TestList
     */
    public TestList() {
        initComponents();
    }

    public TestList(JPanel contentPane, Controller controller) {
        this.controller = controller;
        initComponents();
        this.contentPane = contentPane;
        this.showAllTest();

    }

    public void showAllTest() {
        final Test[] tests = new Test[controller.getTestBank().getTests().size()];
        for (int i = 0; i < controller.getTestBank().getTests().size(); i++) {
            tests[i] = controller.getTestBank().getTestById(i + 1);
        }
        listModel = new AbstractListModel() {
            @Override
            public int getSize() {
                return tests.length;//To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getElementAt(int i) {
                return tests[i]; //To change body of generated methods, choose Tools | Templates.
            }
        };
        listTest.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblInstructions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTest = new javax.swing.JList();
        btnBack = new javax.swing.JButton();
        btnTakeTest = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Snap ITC", 0, 30)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Take a Test");

        lblInstructions.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        lblInstructions.setText("<html>Select a test from the list to take test:</html>");

        listTest.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listTest);

        btnBack.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melt/View/Icons/return.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnTakeTest.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        btnTakeTest.setText("Take Test");
        btnTakeTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 194, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(228, 228, 228)
                                .addComponent(btnTakeTest)))
                        .addGap(0, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTakeTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTakeTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeTestActionPerformed
        // TODO add your handling code here:
        if (listTest.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "You need to select a test first.");
            return;
        }
        CardLayout cardLayout2 = (CardLayout) contentPane.getLayout();
        cardLayout2.show(contentPane, "takeTest");        // TODO add your handling code here:
        StudentPanel panel = (StudentPanel) contentPane.getComponent(2);


        panel.setTest(this.controller.getTest(listTest.getSelectedIndex() + 1));
        panel.startTest();//To change body of generated methods, choose Tools | Templates.
    }//GEN-LAST:event_btnTakeTestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout7 = (CardLayout) contentPane.getLayout();
        cardLayout7.show(contentPane, "welcomePanel");
    }//GEN-LAST:event_btnBackActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTakeTest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList listTest;
    // End of variables declaration//GEN-END:variables
}
